# 서버 포트 설정
server:
  port: 8888

# SpringDoc OpenAPI/Swagger 구성
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

# JPA 공통 설정
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # 이메일 템플릿 공통 설정
  mail:
    properties:
      template: |
        <div style="font-family: 'Apple SD Gothic Neo', 'sans-serif' !important; width: 540px; height: 600px; border-top: 4px solid {point_color}; margin: 100px auto; padding: 30px 0; box-sizing: border-box;">
            <h1 style="margin: 0; padding: 0 5px; font-size: 28px; font-weight: 400;">
               <span style="font-size: 15px; margin: 0 0 10px 3px;">Untitled</span><br />
               <span style="color: {point_color};">메일인증</span> 안내입니다.
            </h1>
            <p style="font-size: 16px; line-height: 26px; margin-top: 50px; padding: 0 5px;">
               안녕하세요.<br />
               '야금야금'에 가입해 주셔서 진심으로 감사드립니다.<br />
               아래 <b style="color: {point_color};">'메일 인증 번호'</b>를 입력하여 메일인증을 완료해 주세요.<br />
               감사합니다.<br/><br/>
            </p>
            <b style="font-size: 40px; color: {$point_color};">메일 인증 번호 : {code}</b>
            <br/><br/><br/>
            <div style="border-top: 1px solid #DDD; padding: 5px;">
               <p style="font-size: 13px; line-height: 21px; color: #555;">
                  만약 인증번호가 정상적으로 보이지않거나 인증이 지속적으로 실패된다면 'sip0518@pusan.ac.kr'로 연락주시면 감사하겠습니다.<br />
               </p>
            </div>
        </div>